name: ci_project

on: [push, pull_request]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install h5py numpy
    - run: python CountMotion.py 30secs/motion.h5 dx -q
